### ISSUE TITLE
Delete it.

### ISSUE THREAD

**Issue by SuperErnD** [predefine/Kifa2#1]

**Comment by predefine** [comment]
why?

**Comment by SuperErnD** [comment]
its closed-source project so

**Comment by predefine** [comment]
It dont have any license

**Comment by SuperErnD** [comment]
it has

**Comment by predefine** [comment]
I didnt see any "LICENSE" file in original repo

**Comment by SuperErnD** [comment]
it contains in migrated repo (https://git.schicksal.im/Kifa/Kifa/src/branch/dev/LICENSE.md)

**Comment by predefine** [comment]
But im pushed github repo lol

**Comment by predefine** [comment]
> it contains in migrated repo

404

**Comment by SuperErnD** [comment]
ok then

**Comment by SuperErnD** [comment]
> > it contains in migrated repo
> 
> 404

wtf its closed-source

**Comment by SuperErnD** [comment]
![image](https://github.com/predefine/Kifa2/assets/84639576/24ca41a3-478f-4baa-ae57-7e5979dd8fe0)

**Comment by SuperErnD** [comment]
so just delete it

**Comment by predefine** [comment]
> > > it contains in migrated repo
> > 
> > 404
> 
> wtf its closed-source

Im cant see license and it wasnt in original github repo, im dont will delete this repo

**Comment by SuperErnD** [comment]
first of all i sent u license, and u arent contacted me
second of all github has outdated source which doesnt have license, but new has it

**Comment by predefine** [comment]
> ![image](https://github.com/predefine/Kifa2/assets/84639576/24ca41a3-478f-4baa-ae57-7e5979dd8fe0)
> 

Okay, but im pushed latest version without LICENSE or LICENSE.md (it wasnt in original repo)

**Comment by SuperErnD** [comment]
yes, but license covers old version first of all
also wiki has the license in original repo

**Comment by predefine** [comment]
> but license also covers old version

Hmm, it like "make gpl2 project, wait many forks and change license to proprietary)

**Comment by SuperErnD** [comment]
previuosly it dont has the license
so ur example is stupid

**Comment by gentoocat** [comment]
> yes, but license also covers old version first of all also wiki has the license in original repo

nope : )

**Comment by gentoocat** [comment]
> ![image](https://user-images.githubusercontent.com/84639576/282314016-24ca41a3-478f-4baa-ae57-7e5979dd8fe0.png)

it has no legal effect btw

**Comment by SuperErnD** [comment]
in short predefine is idiot, i know what license is very stupid, i dont really want to share source, but predefine is sus imposter so he shared it, i hate he

**Comment by SuperErnD** [comment]
![image](https://github.com/predefine/Kifa2/assets/84639576/c9b52484-5b18-49aa-8a04-89419112db8c)
i think what predefine is sus imposter, i will talk about it with he in telegram
